# Generated by Django 2.2.16 on 2020-09-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(verbose_name='user ID in social media')),
                ('name', models.CharField(max_length=20, verbose_name='Username')),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
    ]
